"""
Useful suggestion hints we might want to use
"""

all_pokemon = [
    'Bulbasaur',
    'Ivysaur',
    'Venusaur',
    'Charmander',
    'Charmeleon',
    'Charizard',
    'Squirtle',
    'Wartortle',
    'Blastoise',
    'Caterpie',
    'Metapod',
    'Butterfree',
    'Weedle',
    'Kakuna',
    'Beedrill',
    'Pidgey',
    'Pidgeotto',
    'Pidgeot',
    'Rattata',
    'Raticate',
    'Spearow',
    'Fearow',
    'Ekans',
    'Arbok',
    'Pikachu',
    'Raichu',
    'Sandshrew',
    'Sandslash',
    'Nidoran♀',
    'Nidorina',
    'Nidoqueen',
    'Nidoran♂',
    'Nidorino',
    'Nidoking',
    'Clefairy',
    'Clefable',
    'Vulpix',
    'Ninetales',
    'Jigglypuff',
    'Wigglytuff',
    'Zubat',
    'Golbat',
    'Oddish',
    'Gloom',
    'Vileplume',
    'Paras',
    'Parasect',
    'Venonat',
    'Venomoth',
    'Diglett',
    'Dugtrio',
    'Meowth',
    'Persian',
    'Psyduck',
    'Golduck',
    'Mankey',
    'Primeape',
    'Growlithe',
    'Arcanine',
    'Poliwag',
    'Poliwhirl',
    'Poliwrath',
    'Abra',
    'Kadabra',
    'Alakazam',
    'Machop',
    'Machoke',
    'Machamp',
    'Bellsprout',
    'Weepinbell',
    'Victreebel',
    'Tentacool',
    'Tentacruel',
    'Geodude',
    'Graveler',
    'Golem',
    'Ponyta',
    'Rapidash',
    'Slowpoke',
    'Slowbro',
    'Magnemite',
    'Magneton',
    'Farfetch\'d',
    'Doduo',
    'Dodrio',
    'Seel',
    'Dewgong',
    'Grimer',
    'Muk',
    'Shellder',
    'Cloyster',
    'Gastly',
    'Haunter',
    'Gengar',
    'Onix',
    'Drowzee',
    'Hypno',
    'Krabby',
    'Kingler',
    'Voltorb',
    'Electrode',
    'Exeggcute',
    'Exeggutor',
    'Cubone',
    'Marowak',
    'Hitmonlee',
    'Hitmonchan',
    'Lickitung',
    'Koffing',
    'Weezing',
    'Rhyhorn',
    'Rhydon',
    'Chansey',
    'Tangela',
    'Kangaskhan',
    'Horsea',
    'Seadra',
    'Goldeen',
    'Seaking',
    'Staryu',
    'Starmie',
    'Mr. Mime',
    'Scyther',
    'Jynx',
    'Electabuzz',
    'Magmar',
    'Pinsir',
    'Tauros',
    'Magikarp',
    'Gyarados',
    'Lapras',
    'Ditto',
    'Eevee',
    'Vaporeon',
    'Jolteon',
    'Flareon',
    'Porygon',
    'Omanyte',
    'Omastar',
    'Kabuto',
    'Kabutops',
    'Aerodactyl',
    'Snorlax',
    'Articuno',
    'Zapdos',
    'Moltres',
    'Dratini',
    'Dragonair',
    'Dragonite',
    'Mewtwo',
    'Mew'
]

some_moves = [
    'Absorb',
    'Accelerock',
    'Acid',
    'Acid Armor',
    'Acid Downpour',
    'Acid Spray',
    'Acrobatics',
    'Acupressure',
    'Aerial Ace',
    'Aeroblast',
    'After You',
    'Agility',
    'Air Cutter',
    'Air Slash',
    'All-Out Pummeling',
    'Ally Switch',
    'Amnesia',
    'Anchor Shot',
    'Ancient Power',
    'Aqua Jet',
    'Baby-Doll Eyes',
    'Baddy Bad',
    'Baneful Bunker',
    'Barrage',
    'Barrier',
    'Baton Pass',
    'Beak Blast',
    'Beat Up',
    'Belch',
    'Belly Drum',
    'Bestow',
    'Bide',
    'Bind',
    'Bite',
    'Black Hole Eclipse',
    'Blast Burn',
    'Blaze Kick',
    'Blizzard',
    'Block',
    'Bloom Doom',
    'Blue Flare',
    'Calm Mind',
    'Camouflage',
    'Captivate',
    'Catastropika',
    'Celebrate',
    'Charge',
    'Charge Beam',
    'Charm',
    'Chatter',
    'Chip Away',
    'Circle Throw',
    'Clamp',
    'Clanging Scales',
    'Clangorous Soulblaze',
    'Clear Smog',
    'Close Combat',
    'Coil',
    'Dark Pulse',
    'Dark Void',
    'Darkest Lariat',
    'Dazzling Gleam',
    'Defend Order',
    'Defense Curl',
    'Defog',
    'Destiny Bond',
    'Detect',
    'Devastating Drake',
    'Diamond Storm',
    'Dig',
    'Disable',
    'Disarming Voice',
    'Discharge',
    'Dive',
    'Dizzy Punch',
    'Doom Desire',
    'Earth Power',
    'Earthquake',
    'Echoed Voice',
    'Eerie Impulse',
    'Egg Bomb',
    'Electric Terrain',
    'Electrify',
    'Electro Ball',
    'Electroweb',
    'Embargo',
    'Ember',
    'Encore',
    'Endeavor',
    'Endure',
    'Energy Ball',
    'Entrainment',
    'Eruption',
    'Explosion',
    'Extrasensory',
    'Fiery Dance',
    'Final Gambit',
    'Fire Blast',
    'Fire Fang',
    'Fire Lash',
    'Fire Pledge',
    'Fire Punch',
    'Fire Spin',
    'First Impression',
    'Fissure',
    'Flail',
    'Flame Burst',
    'Flame Charge',
    'Flame Wheel',
    'Flamethrower',
    'Flare Blitz',
    'Flash',
    'Flash Cannon',
    'Flatter',
    'Fleur Cannon',
    'Fling',
    'Floaty Fall',
    'Floral Healing',
    'Flower Shield',
    'Fly',
    'Flying Press',
    'Focus Blast',
    'Focus Energy',
    'Focus Punch',
    'Follow Me',
    'Force Palm',
    'Foresight',
    "Forest\'s Curse",
    'Foul Play',
    'Freeze Shock',
    'Freeze-Dry',
    'Freezy Frost',
    'Frenzy Plant'
]